### PR TITLE
modify module to support ios 64bits

### PR DESCRIPTION
**Pull request by pussaaon**

### CODE REVIEW

**Comment by benjaminfox** [comment]
@pussaaon Thanks very much. We'll evaluate this and bring it in as soon as possible.

**Comment by adambard** [comment]
Thanks for the PR! But, I'm afraid we can't accept it as a binary. Do you have the changes to the source instead?

**Comment by pussaaon** [comment]
@adambard  only thing I changed, it's the required min titanium sdk version here https://github.com/startsiden/tapstream-sdk/commit/581d8a63d17e292ef9fe46e73dbfdd9011685337 ,

what do you mean by changes to the source instead ? about the binary, do you mean the zip file ? you can remove it if you want

**Comment by adambard** [comment]
Ah, was that it? I had imagined there would be more to it, sorry about that. If you could remove the zip file that would be great!

**Comment by pussaaon** [comment]
ok, removed

**Comment by pussaaon** [comment]
thanks for merging to the sdk  :)

**Comment by pussaaon** [comment]
has this been merged ?

**Pull request merged**
